.TH "Camorama" "1" "29 August 2003" "" ""
.SH "NAME"
Camorama \- GNOME2 Video4Linux viewer
.SH "SYNOPSIS"
.B camorama
.RI [ options ]
.SH "DESCRIPTION"
This manual page documents briefly the
.B camorama
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP 

\fBCamorama\fP
is an open\-source Video4Linux application with view, record and even effect capabilities.
.br 
.SH "OPTIONS"
Options:
.TP 
.B \-h
usage
.TP 
.B \-V
version info
.TP 
.B \-D
debugging info
.TP 
.B \-d <video_dev>
use video_dev instead of /dev/video0
.TP 
.B \-M
use maximum capture size (depends on camera)
.TP 
.B \-m
use minimum capture size (depends on camera)
.TP 
.B \-H
use middle capture size (depends on camera)
.TP 
.B \-x <width>
capture width
.TP 
.B \-y <height>
capture height

.SH "AUTHOR"
This manual page was written by Leo Costela Antunes <costela@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
