#define GCONF_PARENT "/apps/camorama"
#define GCONF_PREFS  GCONF_PARENT "/preferences"

#define GCONF_DEVICE                GCONF_PARENT "/device"
#define GCONF_SAVE_DIR              GCONF_PREFS "/save_dir"
#define GCONF_SAVE_FILE             GCONF_PREFS "/save_file"
#define GCONF_FILE_TYPE             GCONF_PREFS "/file_type"
#define GCONF_TIMESTAMP             GCONF_PREFS "/timestamp"
#define GCONF_HOSTNAME              GCONF_PREFS "/hostname"
#define GCONF_REMOTE_PROTO          GCONF_PREFS "/remote_proto"
#define GCONF_REMOTE_SAVE_DIR       GCONF_PREFS "/remote_save_dir"
#define GCONF_REMOTE_SAVE_FILE      GCONF_PREFS "/remote_save_file"
#define GCONF_REMOTE_FILE_TYPE      GCONF_PREFS "/remote_file_type"
#define GCONF_REMOTE_TIMESTAMP      GCONF_PREFS "/remote_timestamp"
#define GCONF_LOCAL_CAPTURE         GCONF_PREFS "/local_capture"
#define GCONF_REMOTE_CAPTURE        GCONF_PREFS "/remote_capture"
#define GCONF_LOCAL_APPEND_TS       GCONF_PREFS "/append_ts_to_file"
#define GCONF_REMOTE_APPEND_TS      GCONF_PREFS "/remote_append_ts_to_file"
#define GCONF_TIMESTAMP_STRING      GCONF_PREFS "/timestamp_string"
#define GCONF_USE_CUSTOM_STRING     GCONF_PREFS "/use_custom_string"
#define GCONF_DRAWDATE              GCONF_PREFS "/drawdate"
#define GCONF_AUTO_CAPTURE          GCONF_PREFS "/auto_capture"
#define GCONF_AUTO_CAPTURE_INTERVAL GCONF_PREFS "/auto_capture_interval"
#define GCONF_SHOW_ADJUSTMENTS      GCONF_PREFS "/show_adjustments"
#define GCONF_SHOW_EFFECTS          GCONF_PREFS "/show_effects"
