#define GCONF_PARENT "/apps/camorama/preferences"

#define GCONF_DEVICE                GCONF_PARENT "/device"
#define GCONF_SAVE_DIR              GCONF_PARENT "/save_dir"
#define GCONF_SAVE_FILE             GCONF_PARENT "/save_file"
#define GCONF_FILE_TYPE             GCONF_PARENT "/file_type"
#define GCONF_TIMESTAMP             GCONF_PARENT "/timestamp"
#define GCONF_HOSTNAME              GCONF_PARENT "/hostname"
#define GCONF_REMOTE_PROTO          GCONF_PARENT "/remote_proto"
#define GCONF_REMOTE_SAVE_DIR       GCONF_PARENT "/remote_save_dir"
#define GCONF_REMOTE_SAVE_FILE      GCONF_PARENT "/remote_save_file"
#define GCONF_REMOTE_FILE_TYPE      GCONF_PARENT "/remote_file_type"
#define GCONF_REMOTE_TIMESTAMP      GCONF_PARENT "/remote_timestamp"
#define GCONF_LOCAL_CAPTURE         GCONF_PARENT "/local_capture"
#define GCONF_REMOTE_CAPTURE        GCONF_PARENT "/remote_capture"
#define GCONF_LOCAL_APPEND_TS       GCONF_PARENT "/append_ts_to_file"
#define GCONF_REMOTE_APPEND_TS      GCONF_PARENT "/remote_append_ts_to_file"
#define GCONF_TIMESTAMP_STRING      GCONF_PARENT "/timestamp_string"
#define GCONF_USE_CUSTOM_STRING     GCONF_PARENT "/use_custom_string"
#define GCONF_DRAWDATE              GCONF_PARENT "/drawdate"
#define GCONF_AUTO_CAPTURE          GCONF_PARENT "/auto_capture"
#define GCONF_AUTO_CAPTURE_INTERVAL GCONF_PARENT "/auto_capture_interval"
#define GCONF_SHOW_ADJUSTMENTS      GCONF_PARENT "/show_adjustments"
#define GCONF_SHOW_EFFECTS          GCONF_PARENT "/show_effects"
